name: tests

on:
  push:
    paths:
      - "**"
      - "!**.md"
  pull_request:
    paths:
      - "**"
      - "!**.md"
  workflow_dispatch:

jobs:
  all_tests:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: linux
            runs-on: ubuntu-22.04
            arch: x86_64

          - os: mac
            runs-on: macos-12
            arch: x86_64

          - os: windows
            runs-on: windows-2022
            arch: x86_64

          - os: linux
            runs-on: ubuntu-22.04
            arch: cross-compile

    name: "${{ matrix.os }}-${{ matrix.arch }}"
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout code
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: On Linux, when not cross-compiling, install musl
        if: matrix.os == 'linux' && matrix.arch == 'x86_64'
        run: ./.github/bin/linux-install-musl

      - name: On Linux, when cross-compiling, install Zig
        if: matrix.os == 'linux' && matrix.arch == 'cross-compile'
        run: ./.github/bin/linux-install-zig

      - name: Install Nim
        uses: iffy/install-nim@1ab2fcc1d8294b3956d5696f45cd470c9fe69466
        with:
          version: "binary:1.6.8"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install our Nimble dependencies
        run: nimble --accept install --depsOnly

      - name: Run our test suite
        env:
          ARCH: ${{ matrix.arch }}
        shell: bash
        run: |
          if [[ "${ARCH}" == 'cross-compile' ]]; then
            nimble test -d:zig
          else
            nimble test
          fi
